export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGGED_IN = 'LOGGED_IN';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOG_OUT = 'LOG_OUT';

export const ADD_DOCTOR = 'ADD_DOCTOR';
export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_SINGLE_DOCTOR = 'GET_SINGLE_DOCTOR';
export const DOCTOR_FILTER = 'DOCTOR_FILTER';

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
